;-*- emacs-lisp -*-
; $Id$
(setq custom-file "~/lib/site-lisp/init-customize.el")

(load "misc-init.el")
(load "japanese_env.el")
(load "ddskk-init.el")
(load "browse-url-init.el")
(load "completions-highlight.el")
(load "dired-mode-init.el")
;(load "fontset-init.el")
(load "howm-init.el")
(load "html-helper-mode-init.el")
(load "liece-init.el")
(load "lookup-init.el")
(load "make-file-executable.el")
(load "mwheel-init.el")
(load "mpg123-init.el")
(load "riece-init.el")
(load "tdiary-mode-init.el")
(load "tiarra-conf-mode-init.el")
(load "tramp-init.el")
(load "shimbun-init.el")
(load "init-wget.el")
(load "init-w3m.el")
(load "wl-init.el")

;(load "ndiary-mode-init.el")
