;-*- emacs-lisp -*-
; $Id$
(setq custom-file "~/lib/site-lisp/customize.el")

(load "init-misc.el")
(load "init-dired-mode.el")
(load "init-ddskk.el")
(load "init-wget.el")
(load "init-w3m.el")
(load "init-shimbun.el")
(load "init-wl.el")
(load "init-browse-url.el")
(load "init-howm.el")
(load "init-html-helper-mode.el")
(load "init-liece.el")
(load "init-riece.el")
(load "init-lookup.el")
(load "init-mwheel.el")
(load "init-mpg123.el")
(load "init-tdiary-mode.el")
(load "init-tiarra-conf-mode.el")
(load "init-tramp.el")
(load "japanese_env.el")
(load "completions-highlight.el")
(load "make-file-executable.el")

;(load "ndiary-mode-init.el")
;(load "fontset-init.el")