;;; packages.el --- A setting of the packages.
;;; Commentary:
;;; Code:

;; For vue-mode.
(el-get-bundle Fanael/edit-indirect)
(el-get-bundle AdamNiederer/ssass-mode)
(el-get-bundle AdamNiederer/vue-html-mode)
(el-get-bundle AdamNiederer/vue-mode)

(el-get-bundle anzu)
(el-get-bundle atomic-chrome)
(el-get-bundle bastibe/org-journal)
(el-get-bundle buffer-move)
(el-get-bundle company-mode)
(el-get-bundle company-quickhelp :depends (pos-tip))
(el-get-bundle daichirata/emacs-rotate)
(el-get-bundle ddskk)
(el-get-bundle docker-tramp)
(el-get-bundle dockerfile-mode)
(el-get-bundle editorconfig)
(el-get-bundle elim/auto-save-buffers-enhanced)
(el-get-bundle elscreen)
(el-get-bundle emacs-helm/helm-elscreen :depends (elscreen helm))
(el-get-bundle flycheck)
(el-get-bundle gist:5457732:ginger-api :depends (json popwin request))
(el-get-bundle gist:666807b53f2b2cf503c1:clipboard-to-kill-ring :depends (deferred))
(el-get-bundle git-modes)
(el-get-bundle glynnforrest/mmm-jinja2)
(el-get-bundle glynnforrest/salt-mode)
(el-get-bundle go-mode)
(el-get-bundle google-translate)
(el-get-bundle helm)
(el-get-bundle helm-ag)
(el-get-bundle helm-css-scss)
(el-get-bundle helm-descbinds)
(el-get-bundle helm-git-grep)
(el-get-bundle helm-projectile)
(el-get-bundle jinja2-mode)
(el-get-bundle js2-mode)
(el-get-bundle json-mode)
(el-get-bundle magit)
(el-get-bundle markdown-mode)
(el-get-bundle migemo)
(el-get-bundle mmm-mode)
(el-get-bundle open-junk-file)
(el-get-bundle php-mode)
(el-get-bundle popwin)
(el-get-bundle rainbow-mode)
(el-get-bundle rejeep/ruby-end.el)
(el-get-bundle rspec-mode)
(el-get-bundle ruby-mode)
(el-get-bundle Simplify/flycheck-typescript-tslint :depends (flycheck))
(el-get-bundle slim-mode)
(el-get-bundle smart-mode-line)
(el-get-bundle terraform-mode)
(el-get-bundle tide)
(el-get-bundle typescript-mode)
(el-get-bundle undo-tree)
(el-get-bundle web-mode)
(el-get-bundle wgrep)
(el-get-bundle yaml-mode)

;;; packages.el ends here
